### ISSUE TITLE
Getting Authenticated Session Cookie Required.

### ISSUE THREAD

**Issue by TheLosingEdge** [l4rm4nd/LinkedInDumper#8]
Getting authenticated session cookie required. Updated li_at and JSESSIONID values and changed user agent strings a couple times and no luck. Maybe Voyager API changed?

**Comment by l4rm4nd** [comment]
Hey @TheLosingEdge,

many thanks for bringing this up. 

Indeed, the voyager API had some small changes, where the JSON response now contains some bogus or empty datasets. This broke my spaghetti code. I've added some try catch statements into the mix in order to skip those empty fields.

Script should work now again. Sorry for the inconvenience.

**Comment by TheLosingEdge** [comment]
Confirming it's working again, thank you!
